# Generated by Django 5.1.7 on 2025-03-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_interests_alter_userprofile_why'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='extravert',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='introvert',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
