# Generated by Django 5.1.7 on 2025-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_extravert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dateOfBirth_str',
            field=models.CharField(default='01/01/2020', max_length=50),
            preserve_default=False,
        ),
    ]
